# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0002_auto_20160513_0229'),
        ('clientes', '0003_auto_20160512_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('validez', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PresupuestoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('horas', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('cobra_en_sesion', models.BooleanField(default=False)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='presupuestos.Presupuesto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='servicios.Servicio')),
            ],
        ),
    ]
