# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='DNI')),
                ('email', models.EmailField(max_length=254)),
                ('observaciones', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre', 'apellido'],
            },
        ),
    ]
