# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
